version: '3'
services:
  rails:
    build: .
    command: "bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'hostname.example.com -> http://rails:3000'
      STAGE: 'local'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
